"""add sessions and page_views tables

Revision ID: 244852b37ebd
Revises: 5893b001fd09
Create Date: 2026-08-04 17:21:28.609956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244852b37ebd'
down_revision: Union[str, Sequence[str], None] = '5893b001fd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_views',
    sa.Column('page_view_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('card_slug', sa.String(), nullable=True),
    sa.CheckConstraint("event_type IN ('issuer_view','card_view')", name='ck_page_view_event_type'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_view_id')
    )
    op.create_index(op.f('ix_page_views_card_slug'), 'page_views', ['card_slug'], unique=False)
    op.create_index(op.f('ix_page_views_issuer'), 'page_views', ['issuer'], unique=False)
    op.create_index(op.f('ix_page_views_occurred_at'), 'page_views', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_page_views_session_id'), 'page_views', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_views_session_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_occurred_at'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_issuer'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_card_slug'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_table('sessions')
    # ### end Alembic commands ###
