"""initial card catalog schema

Revision ID: 4a994c57972e
Revises:
Create Date: 2026-07-18 22:15:04.376130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a994c57972e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benefit_tiers",
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tier_id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "coverage_types",
        sa.Column("coverage_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("coverage_type_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "issuers",
        sa.Column("issuer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("issuer_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "loyalty_programs",
        sa.Column("loyalty_program_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("program_type", sa.String(), nullable=False),
        sa.Column("is_transferable", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "program_type IN ('bank','airline','hotel','other')", name="ck_loyalty_program_type"
        ),
        sa.PrimaryKeyConstraint("loyalty_program_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "networks",
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("network_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cards",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.Integer(), nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.Column("points_program_id", sa.Integer(), nullable=False),
        sa.Column("accent_color", sa.String(), nullable=False),
        sa.Column("annual_fee_cents", sa.Integer(), nullable=False),
        sa.Column("effective_cost_label", sa.String(), nullable=False),
        sa.Column("verdict_status", sa.String(), nullable=False),
        sa.Column("verdict_text", sa.String(), nullable=False),
        sa.Column("earn_note", sa.String(), nullable=True),
        sa.Column("points_note", sa.String(), nullable=True),
        sa.Column("transfer_airline_count", sa.Integer(), nullable=False),
        sa.Column("transfer_hotel_count", sa.Integer(), nullable=False),
        sa.Column("transfer_highlight", sa.String(), nullable=True),
        sa.Column("transfer_recent_changes", sa.String(), nullable=True),
        sa.Column("protection_note", sa.String(), nullable=True),
        sa.Column("rental_note", sa.String(), nullable=True),
        sa.Column("additional_cards_title", sa.String(), nullable=True),
        sa.Column("additional_cards_note", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict_status IN ('keep','situational','reconsider')", name="ck_card_verdict_status"
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.issuer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.network_id"],
        ),
        sa.ForeignKeyConstraint(
            ["points_program_id"],
            ["loyalty_programs.loyalty_program_id"],
        ),
        sa.PrimaryKeyConstraint("card_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "additional_card_options",
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fee_cents", sa.Integer(), nullable=True),
        sa.Column("fee_label", sa.String(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("option_id"),
    )
    op.create_table(
        "card_transfer_partners",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("loyalty_program_id", sa.Integer(), nullable=False),
        sa.Column("transfer_ratio", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["loyalty_program_id"],
            ["loyalty_programs.loyalty_program_id"],
        ),
        sa.PrimaryKeyConstraint("card_id", "loyalty_program_id"),
    )
    op.create_table(
        "credits",
        sa.Column("credit_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("subtitle", sa.String(), nullable=False),
        sa.Column("max_annual_cents", sa.Integer(), nullable=False),
        sa.Column("default_value_cents", sa.Integer(), nullable=False),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.Column("is_removed", sa.Boolean(), nullable=False),
        sa.Column("removed_on", sa.Date(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["benefit_tiers.tier_id"],
        ),
        sa.PrimaryKeyConstraint("credit_id"),
        sa.UniqueConstraint("card_id", "slug", name="uq_credit_card_slug"),
    )
    op.create_table(
        "earn_rates",
        sa.Column("earn_rate_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=True),
        sa.Column("multiplier_x", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("is_highlight", sa.Boolean(), nullable=False),
        sa.Column("is_base", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("earn_rate_id"),
    )
    op.create_table(
        "insurance_benefits",
        sa.Column("insurance_benefit_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("coverage_type_id", sa.Integer(), nullable=False),
        sa.Column("detail", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("level IN ('strong','good','mid','none')", name="ck_insurance_level"),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["coverage_type_id"],
            ["coverage_types.coverage_type_id"],
        ),
        sa.PrimaryKeyConstraint("insurance_benefit_id"),
    )
    op.create_table(
        "redemption_options",
        sa.Column("redemption_option_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("cents_per_point", sa.Float(), nullable=False),
        sa.Column("is_best", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("redemption_option_id"),
    )
    op.create_table(
        "services",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("detail", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id"),
    )
    op.create_table(
        "status_perks",
        sa.Column("status_perk_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("strength BETWEEN 1 AND 5", name="ck_status_perk_strength"),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("status_perk_id"),
    )
    op.create_table(
        "timeline_events",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("date_label", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("badge", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('add','cut','neutral','future')", name="ck_timeline_event_type"
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "additional_card_benefits",
        sa.Column("benefit_id", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("benefit_text", sa.String(), nullable=False),
        sa.Column("is_included", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_id"], ["additional_card_options.option_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("benefit_id"),
    )
    op.create_table(
        "credit_tips",
        sa.Column("credit_tip_id", sa.Integer(), nullable=False),
        sa.Column("credit_id", sa.Integer(), nullable=False),
        sa.Column("tip_text", sa.String(), nullable=False),
        sa.Column("is_warning", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["credit_id"], ["credits.credit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("credit_tip_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credit_tips")
    op.drop_table("additional_card_benefits")
    op.drop_table("timeline_events")
    op.drop_table("status_perks")
    op.drop_table("services")
    op.drop_table("redemption_options")
    op.drop_table("insurance_benefits")
    op.drop_table("earn_rates")
    op.drop_table("credits")
    op.drop_table("card_transfer_partners")
    op.drop_table("additional_card_options")
    op.drop_table("cards")
    op.drop_table("networks")
    op.drop_table("loyalty_programs")
    op.drop_table("issuers")
    op.drop_table("coverage_types")
    op.drop_table("benefit_tiers")
    # ### end Alembic commands ###
