"""add card_drafts review queue

Revision ID: 790e0ec1b9ad
Revises: 4a994c57972e
Create Date: 2026-07-18 22:21:02.535085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790e0ec1b9ad'
down_revision: Union[str, Sequence[str], None] = '4a994c57972e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_drafts',
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('card_slug', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('extracted_json', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_notes', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_draft_status'),
    sa.PrimaryKeyConstraint('draft_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_drafts')
    # ### end Alembic commands ###
