"""drop unused coverage_types.category column

Revision ID: 8f0ff3d3ac9e
Revises: ded6a5344512
Create Date: 2026-08-04 19:13:13.597575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f0ff3d3ac9e"
down_revision: Union[str, Sequence[str], None] = "ded6a5344512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coverage_types", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coverage_types", sa.Column("category", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
