"""add card_feedback table

Revision ID: 93fb9fe16594
Revises: e0689adecdbb
Create Date: 2026-08-11 12:17:11.797565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93fb9fe16594"
down_revision: Union[str, Sequence[str], None] = "e0689adecdbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create card_feedback: one row per visitor's experience of a card.

    A plain create_table, safe on both backends and needing no
    batch_alter_table: the SQLite "NOT NULL needs a server_default" hazard
    only applies when adding a column to an existing table.

    review_status uses a plain string server_default rather than a boolean
    literal on purpose. An earlier draft of this table had a boolean
    is_published, which autogenerate rendered as server_default=sa.text('0')
    because the dev database is SQLite. Postgres rejects 0 as a boolean, so
    that version would have passed locally and failed on Neon.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_feedback",
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("card_slug", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("maximizes_value", sa.String(), nullable=True),
        sa.Column("held_for", sa.String(), nullable=True),
        sa.Column("would_keep", sa.Boolean(), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("review_status", sa.String(), server_default="pending", nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "held_for IS NULL OR held_for IN ('under_6m','6_to_12m','1_to_2y','2_to_5y','over_5y')",
            name="ck_card_feedback_held_for",
        ),
        sa.CheckConstraint(
            "maximizes_value IS NULL OR maximizes_value IN ('yes','partly','no')",
            name="ck_card_feedback_maximizes_value",
        ),
        sa.CheckConstraint(
            "review_status IN ('pending','published','rejected')",
            name="ck_card_feedback_review_status",
        ),
        sa.CheckConstraint("length(comment) <= 1000", name="ck_card_feedback_comment_length"),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_card_feedback_rating_range"),
        sa.PrimaryKeyConstraint("feedback_id"),
        sa.UniqueConstraint("session_id", "card_slug", name="uq_card_feedback_session_card"),
    )
    op.create_index(
        op.f("ix_card_feedback_card_slug"), "card_feedback", ["card_slug"], unique=False
    )
    op.create_index(
        op.f("ix_card_feedback_session_id"), "card_feedback", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_card_feedback_submitted_at"), "card_feedback", ["submitted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_card_feedback_submitted_at"), table_name="card_feedback")
    op.drop_index(op.f("ix_card_feedback_session_id"), table_name="card_feedback")
    op.drop_index(op.f("ix_card_feedback_card_slug"), table_name="card_feedback")
    op.drop_table("card_feedback")
    # ### end Alembic commands ###
