"""Add preference-signal events: detail/value columns + widened event_type check

Adds four page_view event types (credit_slider_set, credit_tier_moved,
card_tab_viewed, issuer_link_clicked) and the two generic columns they
populate.

Hand-written rather than autogenerated: this alters a CheckConstraint, and
SQLite can't ALTER a constraint in place, so both directions run inside
batch_alter_table with the constraint named explicitly. Autogenerate emits a
bare op.create_check_constraint here, which fails locally on SQLite and on a
Postgres downgrade.

Revision ID: a1c4d7e92f30
Revises: f5e891bf35ba
Create Date: 2026-08-06

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1c4d7e92f30"
down_revision: str | Sequence[str] | None = "f5e891bf35ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_EVENT_TYPES = (
    "'issuer_view','card_view','home_view','top_pick_view',"
    "'compare_view','methodology_view','top_pick_card_selected',"
    "'compare_card_selected'"
)
_NEW_EVENT_TYPES = (
    _OLD_EVENT_TYPES + ",'credit_slider_set','credit_tier_moved',"
    "'card_tab_viewed','issuer_link_clicked'"
)


def upgrade() -> None:
    with op.batch_alter_table("page_views", schema=None) as batch_op:
        batch_op.add_column(sa.Column("detail", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("value", sa.String(), nullable=True))
        batch_op.drop_constraint("ck_page_view_event_type", type_="check")
        batch_op.create_check_constraint(
            "ck_page_view_event_type", f"event_type IN ({_NEW_EVENT_TYPES})"
        )
    op.create_index("ix_page_views_detail", "page_views", ["detail"])


def downgrade() -> None:
    op.drop_index("ix_page_views_detail", table_name="page_views")
    # Rows carrying a new event type would violate the narrower constraint
    # this restores, so clear them first. They only exist if the app ran on
    # the newer schema, and losing anonymous interaction analytics on a
    # rollback is preferable to a downgrade that refuses to apply.
    op.execute(
        "DELETE FROM page_views WHERE event_type IN "
        "('credit_slider_set','credit_tier_moved','card_tab_viewed','issuer_link_clicked')"
    )
    with op.batch_alter_table("page_views", schema=None) as batch_op:
        batch_op.drop_constraint("ck_page_view_event_type", type_="check")
        batch_op.create_check_constraint(
            "ck_page_view_event_type", f"event_type IN ({_OLD_EVENT_TYPES})"
        )
        batch_op.drop_column("value")
        batch_op.drop_column("detail")
