"""add indexes to foreign key columns

Revision ID: a45d60514c16
Revises: be0291c77f0a
Create Date: 2026-07-18 23:19:30.968596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a45d60514c16"
down_revision: Union[str, Sequence[str], None] = "be0291c77f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_additional_card_benefits_option_id"),
        "additional_card_benefits",
        ["option_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_additional_card_options_card_id"),
        "additional_card_options",
        ["card_id"],
        unique=False,
    )
    op.create_index(op.f("ix_cards_issuer_id"), "cards", ["issuer_id"], unique=False)
    op.create_index(op.f("ix_cards_network_id"), "cards", ["network_id"], unique=False)
    op.create_index(
        op.f("ix_cards_points_program_id"), "cards", ["points_program_id"], unique=False
    )
    op.create_index(op.f("ix_credit_tips_credit_id"), "credit_tips", ["credit_id"], unique=False)
    op.create_index(op.f("ix_credits_card_id"), "credits", ["card_id"], unique=False)
    op.create_index(op.f("ix_credits_tier_id"), "credits", ["tier_id"], unique=False)
    op.create_index(op.f("ix_earn_rates_card_id"), "earn_rates", ["card_id"], unique=False)
    op.create_index(
        op.f("ix_insurance_benefits_card_id"), "insurance_benefits", ["card_id"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_benefits_coverage_type_id"),
        "insurance_benefits",
        ["coverage_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_redemption_options_card_id"), "redemption_options", ["card_id"], unique=False
    )
    op.create_index(op.f("ix_services_card_id"), "services", ["card_id"], unique=False)
    op.create_index(op.f("ix_status_perks_card_id"), "status_perks", ["card_id"], unique=False)
    op.create_index(
        op.f("ix_timeline_events_card_id"), "timeline_events", ["card_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeline_events_card_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_status_perks_card_id"), table_name="status_perks")
    op.drop_index(op.f("ix_services_card_id"), table_name="services")
    op.drop_index(op.f("ix_redemption_options_card_id"), table_name="redemption_options")
    op.drop_index(op.f("ix_insurance_benefits_coverage_type_id"), table_name="insurance_benefits")
    op.drop_index(op.f("ix_insurance_benefits_card_id"), table_name="insurance_benefits")
    op.drop_index(op.f("ix_earn_rates_card_id"), table_name="earn_rates")
    op.drop_index(op.f("ix_credits_tier_id"), table_name="credits")
    op.drop_index(op.f("ix_credits_card_id"), table_name="credits")
    op.drop_index(op.f("ix_credit_tips_credit_id"), table_name="credit_tips")
    op.drop_index(op.f("ix_cards_points_program_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_network_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_issuer_id"), table_name="cards")
    op.drop_index(op.f("ix_additional_card_options_card_id"), table_name="additional_card_options")
    op.drop_index(
        op.f("ix_additional_card_benefits_option_id"), table_name="additional_card_benefits"
    )
    # ### end Alembic commands ###
