"""add points_per_100k_label to cards

Revision ID: be0291c77f0a
Revises: 790e0ec1b9ad
Create Date: 2026-07-18 22:59:09.816290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be0291c77f0a"
down_revision: Union[str, Sequence[str], None] = "790e0ec1b9ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column("points_per_100k_label", sa.String(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "points_per_100k_label")
    # ### end Alembic commands ###
