"""add device_type to sessions

Revision ID: ddb6cc70abfa
Revises: 8f0ff3d3ac9e
Create Date: 2026-08-04 21:51:46.599607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb6cc70abfa'
down_revision: Union[str, Sequence[str], None] = '8f0ff3d3ac9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('device_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'device_type')
    # ### end Alembic commands ###
