"""add points_pool_id to cards

Revision ID: f3b7589665a8
Revises: 0ebfeee4e39d
Create Date: 2026-07-31 17:16:03.623958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3b7589665a8"
down_revision: Union[str, Sequence[str], None] = "0ebfeee4e39d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("points_pool_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "points_pool_id")
    # ### end Alembic commands ###
