// Generates the routing rules in render.yaml from the same route list the
// prerender step uses.
//
// WHY THESE ARE ENUMERATED RATHER THAN A PATTERN
//
// The rules used to be one pattern per shape: `/cards/:id` rewritten to
// `/cards/:id/index.html`. That is shorter, and it was wrong for every id that
// is not a real card. Measured against production:
//
//   /cards/amex-platinum   -> 200, the card page
//   /cards/does-not-exist  -> 200, zero bytes
//
// A rewrite whose destination does not exist does not 404 and does not fall
// through to the next rule. Render answers 200 with an empty body, so a stale
// or mistyped card link rendered a blank white page and the app never loaded
// to say otherwise. CardDetailPage has handled this correctly the whole time —
// it reads the API's 404, sets noindex and renders "Card not found" — it was
// simply never given the chance to run.
//
// Two ways to fix that. Redirect `/cards/:id` to `/cards/:id/`, which Render
// serves natively, letting unknown ids fall through; that scales forever but
// changes the canonical form of 121 URLs. Or enumerate, so a rule exists only
// where a file exists and everything else reaches the catch-all. Enumerating
// was chosen to keep every URL and canonical exactly as it is.
//
// The cost is that this file has to be regenerated when the catalog changes.
// `tests/renderRoutes.test.ts` fails when it has not been. The failure mode if
// it ever slips past that test is mild by construction: a card with no rule
// falls to the catch-all and still renders, losing only its prerendered
// social-preview tags, which is a long way from a blank page.

import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadRoutes } from "./routes.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
export const RENDER_YAML = join(HERE, "..", "..", "render.yaml");

export const BEGIN = "      # BEGIN GENERATED ROUTES";
export const END = "      # END GENERATED ROUTES";

/**
 * The rules, as YAML, for a list of route paths.
 *
 * "/" is deliberately absent: the root index.html is served natively and a
 * rule for it would be a no-op. Every other prerendered route gets a rewrite
 * onto the file that actually exists, because Render serves a directory's
 * index.html only for paths that end in a slash, and none of ours do.
 *
 * The catch-all stays last and is what makes unknown paths work: client-side
 * routing, and the app's own "Card not found" page.
 */
export function renderRoutesYaml(paths) {
  const rules = paths
    .filter((path) => path !== "/")
    .sort()
    .map(
      (path) =>
        `      - type: rewrite\n        source: ${path}\n        destination: ${path}/index.html`,
    );
  return [
    BEGIN,
    "      # Generated by frontend/scripts/renderRoutes.mjs — run `npm run generate:routes`",
    "      # in frontend/ after adding or removing a card. Do not edit by hand.",
    "      # Enumerated, not patterned, so an unknown id reaches the catch-all",
    "      # instead of rewriting onto a file that does not exist (which Render",
    "      # answers with 200 and an empty body). See that file for the detail.",
    ...rules,
    "      # Everything else: client-side routing, and the app's 404 page.",
    "      - type: rewrite",
    "        source: /*",
    "        destination: /index.html",
    END,
  ].join("\n");
}

/** Splices a generated block between the markers, leaving the rest alone. */
export function spliceRoutes(yaml, block) {
  const start = yaml.indexOf(BEGIN);
  const end = yaml.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error(
      `render.yaml is missing the ${BEGIN.trim()} / ${END.trim()} markers, so there ` +
        `is nowhere to write the routes. Restore them rather than removing this check.`,
    );
  }
  if (end < start) {
    throw new Error("render.yaml has the route markers in the wrong order.");
  }
  return yaml.slice(0, start) + block + yaml.slice(end + END.length);
}

export async function generate() {
  const routes = await loadRoutes();
  const yaml = await readFile(RENDER_YAML, "utf-8");
  return {
    routes,
    next: spliceRoutes(yaml, renderRoutesYaml(routes.map((r) => r.path))),
    current: yaml,
  };
}

// Only when run directly, so importing this from a test does not rewrite the file.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { routes, next, current } = await generate();
  if (next === current) {
    console.log(`[routes] render.yaml already matches ${routes.length} routes`);
  } else {
    await writeFile(RENDER_YAML, next, "utf-8");
    console.log(`[routes] wrote ${routes.length - 1} rewrite rules to render.yaml`);
  }
}
